- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: update apt cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-config.yml
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml