- name: git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "github@felixdorn.fr"
- name: git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Félix Dorn"
- name: global gitignore
  git_config:
    name: core.excludedFiles
    scope: global
    value: "{{ lookup('env', 'HOME') }}/.gitignore"
- name: git default branch
  git_config:
    name: init.defaultBranch
    scope: global
    value: main